In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('iris.csv')

In [3]:
df.head

<bound method NDFrame.head of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [4]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [5]:
df.duplicated().sum()

3

In [6]:
df=df .drop_duplicates()

In [7]:
df1=df

In [8]:
X = df.drop('species' , axis='columns')
Y = df['species']

In [9]:
"""from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=42)
X_res, y_res = ros.fit_resample(X, Y) """

'from imblearn.over_sampling import RandomOverSampler\nros = RandomOverSampler(random_state=42)\nX_res, y_res = ros.fit_resample(X, Y) '

In [10]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,Y, random_state=42,test_size=0.2)

In [11]:
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()

In [12]:
model1.fit(xtrain,ytrain)

LogisticRegression()

In [13]:
print((ytrain == model1.predict(xtrain)).sum()/len(xtrain))

0.9829059829059829


In [14]:
print((ytest == model1.predict(xtest)).sum()/len(xtest))

0.9333333333333333


In [15]:
from sklearn.metrics import confusion_matrix
train_conf = confusion_matrix(ytrain,model1.predict(xtrain))
print(train_conf)

[[37  0  0]
 [ 0 38  2]
 [ 0  0 40]]


In [16]:
trainAcc_0 = train_conf[0][0]/train_conf[0].sum()
print(trainAcc_0)

trainAcc_1 = train_conf[1][1]/train_conf[1].sum()
print(trainAcc_1)

1.0
0.95


In [17]:
test_conf = confusion_matrix(ytest,model1.predict(xtest))
print(test_conf)
testAcc_0 = test_conf[0][0]/test_conf[0].sum()
print(testAcc_0)

testAcc_1 = test_conf[1][1]/test_conf[1].sum()
print(testAcc_1)

[[11  0  0]
 [ 0  9  1]
 [ 0  1  8]]
1.0
0.9


In [18]:
from sklearn.metrics import accuracy_score
predictions = model1.predict(xtest)
print('\nAccuracy Score=',accuracy_score(ytest, predictions))


Accuracy Score= 0.9333333333333333


In [19]:
from sklearn.metrics import classification_report
print(classification_report(ytest, predictions))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       0.90      0.90      0.90        10
   virginica       0.89      0.89      0.89         9

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30

